FROM node:20-alpine as builder

WORKDIR /app

COPY pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages ./packages
COPY . .

RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile
RUN pnpm -F shared-types build
RUN pnpm build

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/public ./public
COPY package.json ./

EXPOSE 3000

CMD ["npm", "start"]
